name: Build

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build.yml'
      - '**/*.hpp'
      - '**/*.cpp'
      - 'CMakeLists.txt'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/build.yml'
      - '**/*.hpp'
      - '**/*.cpp'
      - 'CMakeLists.txt'

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: >
          cmake --no-warn-unused-cli
          -DCMAKE_COMPILE_WARNING_AS_ERROR=ON
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DFREDDY_STATS=ON
          -DFREDDY_TEST=ON
          -B build/${{ matrix.build_type }}

      - name: Build FrEDDY
        # Windows has a multi-config generator
        run: cmake --build build/${{ matrix.build_type }} --config ${{ matrix.build_type }}
