name: CI/CD

on:
  pull_request:
    paths:
      - '.github/workflows/ci-cd.yml'
      - 'CMakeLists.txt'
      - '.clang-tidy'
      - '**/*.cpp'
      - '**/*.hpp'
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  REF: ${{ github.head_ref || github.run_id }}

jobs:
  clang:
    name: Clang (macOS)
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install cache
        run: |
          brew install ccache
          echo "CACHE_DIR=$(ccache --get-config cache_dir)" >> $GITHUB_ENV

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}
          key: ccache-${{ github.job }}-${{ env.REF }}-${{ github.event.repository.pushed_at }}
          restore-keys: ccache-${{ github.job }}-${{ env.REF }}-

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build/_deps
          key: deps-${{ github.job }}-${{ env.REF }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: deps-${{ github.job }}-${{ env.REF }}-

      - name: Configure project
        run: cmake -G Ninja -B build -DCMAKE_COMPILE_WARNING_AS_ERROR=ON -DFREDDY_STATS=ON -DFREDDY_TEST=ON

      - name: Build binaries
        run: cmake --build build

  msvc:
    name: MSVC (Windows)
    runs-on: windows-latest
    defaults:
      run:
        shell: bash # since the default shell on Windows runners was changed to PowerShell

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install cache
        run: |
          choco install ccache
          echo "CACHE_DIR=$(ccache --get-config cache_dir)" >> $GITHUB_ENV

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_DIR }}
          key: ccache-${{ github.job }}-${{ env.REF }}-${{ github.event.repository.pushed_at }}
          restore-keys: ccache-${{ github.job }}-${{ env.REF }}-

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build/_deps
          key: deps-${{ github.job }}-${{ env.REF }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: deps-${{ github.job }}-${{ env.REF }}-

      - name: Configure project
        run: cmake -B build -DCMAKE_COMPILE_WARNING_AS_ERROR=ON -DFREDDY_STATS=ON -DFREDDY_TEST=ON

      - name: Build binaries
        run: cmake --build build
