name: Test

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/test.yml'
      - '**/*.hpp'
      - '**/*.cpp'
      - 'CMakeLists.txt'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/test.yml'
      - '**/*.hpp'
      - '**/*.cpp'
      - 'CMakeLists.txt'

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Configure CMake
        run: cmake -DFREDDY_TEST=ON -B build

      - name: Build FrEDDY
        run: cmake --build build

      - name: Run tests
        working-directory: ${{ github.workspace }}/build
        run: ctest --rerun-failed --output-on-failure
        
      - name: Collect coverage
        working-directory: ${{ github.workspace }}/build
        run: |
          CVG=$(ctest -T Coverage | grep -o '[^ ]*%' | sed 's/%//')
          if [ $(bc <<< "$CVG < 80") -eq 1 ]; then
            exit 1
          fi
